[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci',
  'cd frontend && npm ci', 
  'cd backend && npm ci'
]

[phases.build]
cmds = [
  'cd frontend && npm run build',
  'cd backend && npx prisma generate && npm run build'
]

[start]
cmd = 'cd backend && npx prisma generate && npx prisma migrate deploy && npm start'